apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-logger
  annotations:
    github.com/project-slug: RosaCordeiro/api-logger
spec:
  type: other
  lifecycle: unknown
  owner: guests
